name: snyk-sast-scan-c-code
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1
on:
  push:
    branches:
      - main
jobs:
  snyk-sast-scan:
    steps:
      - name: checkout assert
        uses: cloudbees-io/checkout@v1
      - name: snyk sast
        uses: cloudbees-io/snyk-sast-scan-code@v1
        with:
          orgname: ${{ vars.SNYK_ORG_NAME }}
          token: ${{ secrets.SNYK_SECRET }}
          language: LANGUAGE_C